-- Справочник MPA-рейтингов
CREATE TABLE IF NOT EXISTS mpa_ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);

-- Справочник жанров
CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

-- Пользователи
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE
);

-- Фильмы
CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER NOT NULL,
    mpa_rating_id INTEGER REFERENCES mpa_ratings(id)
);

-- Жанры фильмов (many-to-many)
CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT REFERENCES films(id),
    genre_id INTEGER REFERENCES genres(id),
    PRIMARY KEY (film_id, genre_id)
);

-- Лайки фильмов
CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT REFERENCES films(id),
    user_id BIGINT REFERENCES users(id),
    PRIMARY KEY (film_id, user_id)
);

-- Дружба (односторонняя с подтверждением)
CREATE TABLE IF NOT EXISTS friendships (
    user_id BIGINT REFERENCES users(id),
    friend_id BIGINT REFERENCES users(id),
    status VARCHAR(20) DEFAULT 'UNCONFIRMED',
    PRIMARY KEY (user_id, friend_id)
);
